### ISSUE TITLE
[JOSS Review] Errors in tutorial notebooks

### ISSUE THREAD

**Issue by elbeejay** [davemlz/eemont#18]
Hello, I was running through the tutorial notebooks (locally) and ran into the following errors:

`004-Computing-Spectral-Indices-Landsat-8.ipynb`, I received the following error in the final cell:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-e652de6f3203> in <module>
      2 Map.addLayer(L8.select('GNDVI'),visParamsGNDVI,'GNDVI')
      3 Map.addLayer(L8.select('NDWI'),visParamsNDWI,'NDWI')
----> 4 Map.add_colorbar(visParamsGNDVI['palette'], caption = 'GNDVI')
      5 Map.add_colorbar(visParamsNDWI['palette'], caption = 'NDWI')
      6 Map.addLayerControl()

~/anaconda3/envs/eemont/lib/python3.9/site-packages/geemap/geemap.py in add_colorbar(self, vis_params, cmap, discrete, label, orientation, position, transparent_bg, layer_name, **kwargs)
   2605 
   2606         if not isinstance(vis_params, dict):
-> 2607             raise TypeError("The vis_params must be a dictionary.")
   2608 
   2609         if orientation not in ["horizontal", "vertical"]:

TypeError: The vis_params must be a dictionary.
```
I had similar errors in tutorials 005 and 006 as well.

---

Then in `013-Time-Series-By-Region-Pandas.ipynb`, I had the following code-error combo.
Code block:
```
tsPandas = pd.melt(tsPandas,
                   id_vars = ['system:index','reducer','date'],
                   value_vars = ['GNDVI','EVI'],
                   var_name = 'Index',
                   value_name = 'Value')
```
Error:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-11-bd846c0b8d50> in <module>
----> 1 tsPandas = pd.melt(tsPandas,
      2                    id_vars = ['system:index','reducer','date'],
      3                    value_vars = ['GNDVI','EVI'],
      4                    var_name = 'Index',
      5                    value_name = 'Value')

~/anaconda3/envs/eemont/lib/python3.9/site-packages/pandas/core/reshape/melt.py in melt(frame, id_vars, value_vars, var_name, value_name, col_level, ignore_index)
     62             missing = Index(com.flatten(id_vars)).difference(cols)
     63             if not missing.empty:
---> 64                 raise KeyError(
     65                     "The following 'id_vars' are not present "
     66                     f"in the DataFrame: {list(missing)}"

KeyError: "The following 'id_vars' are not present in the DataFrame: ['system:index']"
```
I ran into a similar error in tutorial 014 as well.

---

I had no issues running tutorials 001, 002, or 003. For tutorials 007 and 008, I wasn't able to get the maps to load, but this may be an error (or impatience) on my end, as the "Loading widget..." text did come up. 

This issue relates to the ongoing [JOSS Review](https://github.com/openjournals/joss-reviews/issues/3168) of this package.

**Comment by davemlz** [comment]
Hi, @elbeejay!

The error of the tutorials 004, 005 and 006 is related to how `geemap` is imported. Since the tutorials were created to work in Google Colab, `geemap` methods are related to `folium` and not to `ipyleaflet`. When you run the notebooks locally, `geemap` uses `ipyleaflet` by default, this can be modified by importing `geemap` as follows:

```python
import geemap.eefolium as geemap
```

That should work for those tutorials. (I will add a comment indicating this in the tutorials, thank you for pointing this out!)

In the case of tutorials 013 and 014, this error is related to the EarthEngine API since it is not longer returning the `system:index` property anymore. I have to modify these two tutorials.

I will modify the tutorials and I'll let you know!

Thank you very much!

**Comment by davemlz** [comment]
Hi, @elbeejay!

I have modified the tutorials.

Let me know if they work!

Cheers!

**Comment by elbeejay** [comment]
The revised examples all worked for me with the exception of tutorial 012. I had to fiddle a bit with the import statement and colorbar statements to get the plots to show up properly.

**Comment by davemlz** [comment]
I'm sorry, now that I checked that tutorial again I see that it was a bit confusing. I have modified it. Let me know if it works!

**Comment by elbeejay** [comment]
This worked, thanks

**Comment by giswqs** [comment]
@davemlz I just improved the geemap `add_colorbar()` function (https://github.com/giswqs/geemap/commit/dc7e54856694a1994b6d4f4044385babe04bd086), making it compatible with both folium and ipyleaflet. It should be available in the next geemap release. You can also run `geemap.update_package()` to install geemap from GitHub. With the improved `add_colorbar()` function, your notebooks will no longer run into errors, and you can just use `import geemap` rather than `geemap.eefolium as geemap`. In short, you notebooks should work with both Colab and local Jupyter without making any changes. 

![image](https://user-images.githubusercontent.com/5016453/116496189-7a81d800-a872-11eb-8b8f-caa62abca1b2.png)

**Comment by giswqs** [comment]
@davemlz I just released geemap [v0.8.15](https://github.com/giswqs/geemap/releases/tag/v0.8.15), which includes the improved `add_colorbar` function. Your notebooks will now work with both Colab and local Jupyter notebooks without making any changes. Also note that `Map.addLayerControl()` is not needed. geemap will automatically add the layer control when the map is displayed in Colab. `Map = geemap.Map()` automatically handles `ee.Authenticate()` and `ee.Initialize()`. Therefore, if you can write `Map = geemap.Map()` after `import geemap`, you will not need  `ee.Authenticate()` or `ee.Initialize()`

https://github.com/openjournals/joss-reviews/issues/3168

**Comment by davemlz** [comment]
That's great! I will update the notebooks. Thank you very much, @giswqs!

**Comment by davemlz** [comment]
I have updated the tutorials (https://github.com/davemlz/eemont/commit/320c867413aa8176bc3abe7a531ebc1ee0d225be). Thank you @giswqs for the update in `geemap`! However, I had some trouble in [Tutorial 012](https://github.com/davemlz/eemont/blob/master/tutorials/012-Spectral-Indices-MODIS-MOD09GA.ipynb) when using the `colormaps`. I think it is caused by the return type of the `Box` object, converting it to a list solved the problem. I can open an Issue in the repository of `geemap` with the full code and errors.
