### ISSUE TITLE
[Possible feature?] Points and polygons from plus codes

### ISSUE THREAD

**Issue by aazuspan** [davemlz/eemont#23]
Hi @davemlz. First of all, eemont is a great tool. Thanks for creating it!

I'm not sure if you're familiar with [open location code](https://github.com/google/open-location-code), but it's a geocoding tool that generates more readable coordinates (aka plus codes) from latitude/longitude (e.g. `[39.777062, -105.006438]` == `85FPQXGV+RC`). Plus codes can also be shortened by including a nearby location (e.g. `85FPQXGV+RC` == `QXGV+RC Denver, CO`).

It would be handy to have a tool for generating EE geometries from plus codes, and I was wondering if you think it would fit in eemont? Unfortunately there are no open web APIs that I know of to decode plus codes, so it would require adding [openlocationcode](https://github.com/google/open-location-code/tree/main/python) as a dependency.

As far as implementation, I'm thinking it would extend `ee.Geometry` with a few static methods using your decorators. To handle shortened plus codes, an address could be geocoded using the same approach you use for `ee.Geometry.PointFromQuery`. Another feature might be the ability to retrieve a plus code from an `ee.Geometry.Point`. Usage might look something like below.

```python
# Create a point from a full plus code
pt = ee.Geometry.PointFromPlusCode("85FPQXGV+RC")
# Create a point from a partial plus code and a nearby location reference
pt = ee.Geometry.PointFromPlusCode("QXGV+RC Denver, CO")
# Create a polygon from a list of plus codes
poly = ee.Geometry.PolygonFromPlusCodes(
    ["85GGXXJ2+R6"],
    ["85GVXVRV+5H"],
    ["859V2WJG+FQ"],
    ["859G2WQH+XF"]
)

# Create a point from coordinates
pt = ee.Geometry.Point([39.777062, -105.006438])
# Get the plus code of the point
pt.plus_code()

>> "85FPQXGV+RC"
```
If you think this would fit in eemont and it's worth adding another dependency for the feature, I'd be happy to implement and make a PR. If not, no worries! It could work as a little standalone package instead.

**Comment by davemlz** [comment]
Hi, @aazuspan!

This is a really awesome idea! I heard about Plus Codes last year and I think they're amazing and a perfect fit for eemont, as you are saying!

There is just one issue with [openlocationcode](https://github.com/google/open-location-code): it is not on conda-forge, and right now I'm waiting for the conda-forge team for the review of eemont. But I think we can tackle this issue. I'll explain the idea here:

Since each Plus Code represents a pair of coordinates, I think that we can create constructors for all EE geometries:

- `ee.Geometry.PointFromPlusCode`
-  `ee.Geometry.MultiPointFromPlusCode`
- `ee.Geometry.PolygonFromPlusCode`
- `ee.Geometry.MultiPolygonFromPlusCode`
- `ee.Geometry.LineStringFromPlusCode`
- `ee.Geometry.MultiLineStringFromPlusCode`
- `ee.Geometry.LinearRingFromPlusCode`
- `ee.Geometry.RectangleFromPlusCode`
- `ee.Geometry.BBoxFromPlusCode`

All these constructors require a pair of coordinates, or a list of pairs of coordinates, or a nested list of pairs of coordinates. Taking this into account, I think that a private function can be created in the `common.py` (this is the module where I store all common functions for extending EE objects) that converts a Plus Code, or a list of Plus Codes, or a nested list of Plus Codes, into a pair of coordinates, a list of pairs of coordinates, or a nested list of pairs of coordinates, and then, create each one of the constructors in the `geometry.py` module using this private function from the `common.py` module.

However, we still have the `openlocationcode` issue. I think we can still use it as a *Soft Dependency*. We can use the package (that is available from PyPI), but without listing it in the `requirements` of eemont. See this:

```python
def _convert_pluscode_to_coordinates(pluscode):
    """Converts a Plus Code, or a list of Plus Codes, into a pair of coordinates, or a list of pairs of coordinates.

    Parameters
    ---------------
    pluscode: str, list[str]
        Plus Code, or list of Plus Codes.

    Returns
    -------
    list
        Coordinates, or list of coordinates.
    """
    try:
        import openlocationcode
    except:
        raise Exception("openlocationcode could not be loaded. Please make sure openlocation code is installed...")

    coordinates = "something..."

    return coordinates
```

I think that in this way we can avoid requiring `openlocationcode` as a dependency, but still using it. Of course it is just a simple example, but we can give more detailed instructions to the community, or create a more robust function that installs the package. After this function is created (in the `common.py` module), the constructors in the `geometry.py` module can be created by using it:

```python
from .common import _convert_pluscode_to_coordinates

@_extend_staticmethod_eeGeometry()
def PointFromPlusCode(pluscode):
    """Constructs an ee.Geometry describing a point from a pluscode by using the openlocationcode package.

    Tip
    ----------
    Check more info about constructors in the :ref:`User Guide<Constructors>`.

    Parameters
    ----------
    pluscode: str
        Plus Code.

    Returns
    -------
    ee.Geometry.Point
        Geometry describing a point from the specified pluscode.

    See Also
    --------
    MultiPointFromPlusCode : Constructs an ee.Geometry describing a MultiPoint from a pluscode by using the openlocationcode package.

    Examples
    --------
    >>> import ee, eemont
    >>> ee.Authenticate()
    >>> ee.Initialize()
    >>> ee.Geometry.PointFromPlusCode("85GGXXJ2+R6")
    """
    coordinates = _convert_pluscode_to_coordinates(pluscode)
    return ee.Geometry.Point(coordinates)
```

What do you think?

Ah! And the idea of retrieving the PlusCode from a point is great! Just one thing, by following the standard names of Earth Engine, I'm trying not to use "_" for public functions, maybe renaming it as:

```python
# Create a point from coordinates
pt = ee.Geometry.Point([39.777062, -105.006438])
# Get the plus code of the point
pt.plusCode()
>> "85FPQXGV+RC"
```

And since this one is not a static method, another decorator must be created.

Let me know if you're interested in adding these features, and I'd be more than happy if you implement it! :) Just let me know and I'll assign you this Issue, I'll create the decorator that is required for the `geometry.py` module and then you can submit the PR!

Oh! And before I forget, in the `tests` folder there is a file for the `geometry.py` module (`test_geometry.py`). There you can test the features!

**Comment by aazuspan** [comment]
That sounds like a solid design! And I think the soft dependency is a good workaround for the conda-forge issue. I'll also open an issue at openlocationcode suggesting they add it to conda-forge, but I don't think development is very active there. 

Please do assign me this issue and create the non-static decorator whenever you get the chance. I'll start putting together the features and tests and submit a PR when they're ready!

**Comment by davemlz** [comment]
Perfect! I'll create the decorator and let you know!

PD: Let's hope the guys at `openlocationcode` see the issue!

Thank you, @aazuspan!

**Comment by davemlz** [comment]
I have added new decorators for `ee.Geometry`, `ee.Feature` and `ee.FeatureCollection` object classes:

```python
@_extend_eeGeometry()
@_extend_eeFeature()
@_extend_eeFeatureCollection()
```

For this case, the decorator for `ee.Geometry` would be the one. I was thinking that the `.plusCode()` method could be maybe added for the `ee.Feature` class, but I'm not sure about it.

Let me know!

And if you require anything, just tell me! :)

**Comment by aazuspan** [comment]
Hi @davemlz, thanks for adding the decorators. The `.plusCode` method will work for `ee.Geometry` or `ee.Feature` objects. 

This feature is mostly implemented and working--just some formatting, docstrings, cleanup, and a tutorial notebook to do--but I had a couple design questions for you. 

1. In order to convert short plus codes (i.e. "QXGV+XH Denver, CO, USA") to geometries, the reference location needs to be geocoded into a lat/lng coordinate. For now, I just copied your geocoding function from [`geometry.PointFromQuery`](https://github.com/aazuspan/eemont/blob/7f5d096a83ff0fc81b9377e70ae3115efeaa0342/eemont/geometry.py#L108) into [`common._lnglat_from_query`](https://github.com/aazuspan/eemont/blob/7f5d096a83ff0fc81b9377e70ae3115efeaa0342/eemont/common.py#L1136)) and had it return the coordinates instead of a geometry. This works fine for my code, but there might be a cleaner way to implement this that reduces code duplication. Any thoughts?
2. I've implemented all the relevant Geometry constructors from plus codes, but I haven't implemented matching Feature constructors. Unlike your query constructors (i.e. `ee.Feature.PointFromQuery`) there won't be any interesting metadata properties to add to the feature. But they would be quick to implement, so if you think they'll be useful I'll do that.

**Comment by davemlz** [comment]
Hi, @aazuspan!

That's great! I really like what you're doing :)

Regarding question 1, let me handle it, I'll create some core methods to avoid code duplication. I'll let you know when it is ready!

Regarding question 2, don't worry, if there are no interesting metadata to add, it is better just to keep just the Geometry constructors :)

Thank you!

**Comment by davemlz** [comment]
Hi, @aazuspan!

Two new things:

1. I've changed the decorators. I deleted all previous decorators and created a single cleaner decorator. Check the usage:

```python
from .extending import extend

@extend(ee.geometry.Geometry, static=True)
def PointFromPlusCode(something):
    return something

@extend(ee.geometry.Geometry)
def plusCode(something):
    return something
```

2. I've created two geocoding utils: [_retrieve_location()](https://github.com/davemlz/eemont/blob/3943133a34d7056221194f10c8ac36c38fae2e37/eemont/common.py#L1029) and [_lnglat_from_location()](https://github.com/davemlz/eemont/blob/3943133a34d7056221194f10c8ac36c38fae2e37/eemont/common.py#L1058): Check the usage:

```python
from .common import _retrieve_location
from .common import _lnglat_from_location

# If you require only one location, exactly_one must be True
location = _retrieve_location(query = query, geocoder = geocoder, exactly_one = True, **kwargs)
lnglat = _lnglat_from_location(location)
```

I think that with those methods both `queries` and `plus-codes` methods should work.

Let me know if they work or if you need anything else! :)

**Comment by aazuspan** [comment]
Nice changes @davemlz! I like the new decorator system. 

This should work great for me, but I'll let you know if I have any other questions. Thanks!
