### ISSUE TITLE
getTimeSeriesByRegion returns empty and repeated dates in dataframe

### ISSUE THREAD

**Issue by mariofomacajr** [davemlz/eemont#72]
**Describe the bug**
When I extract a timeserie by point the final dataframe return a lot of empty rows for the same date. Sometimes the NDVI value appears only in one row.

![image](https://user-images.githubusercontent.com/65542862/177813705-b60d6b73-4719-4e5a-9aac-06c0d32f4039.png)

**Additional context**
[github eemont.zip](https://github.com/davemlz/eemont/files/9065349/github.eemont.zip)

**Comment by davemlz** [comment]
Hi @mariofomacajr!

I just checked your code and everything is working fine :) You're getting exactly 4 images per day because your point is actually getting 4 different tiles of S2 (T22JCP, T22JCN, T22JBP, T22JBN).

You can do: After getting the time series as a data frame group by day and compute the average (or median) using `pandas` itself, or you can use [`wxee`](https://github.com/aazuspan/wxee) to do it before downloading the data. It is up to you!

Best,

David
